version: '3'
services:
  injector-nmap:
    image: openbas/injector-nmap:1.18.8
    environment:
      - OPENBAS_URL=http://localhost
      - OPENBAS_TOKEN=ChangeMe
      - INJECTOR_ID=ChangeMe
      - "INJECTOR_NAME=Nmap"
      - INJECTOR_LOG_LEVEL=error
    restart: always
