version: '3'
services:
  injector-aws:
    image: openbas/injector-aws:1.18.16
    environment:
      - OPENBAS_URL=http://localhost
      - OPENBAS_TOKEN=ChangeMe
      - INJECTOR_ID=ChangeMe
      - "INJECTOR_NAME=AWS"
      - INJECTOR_LOG_LEVEL=error
    restart: always